/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\近期任务\\myBlog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-7b515403",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b515403").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b192d922",
    path: "/views/env/Linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b192d922").then(next)
    },
  },
  {
    path: "/views/env/Linux常用命令.html",
    redirect: "/views/env/Linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: "/views/env/Linux常用命令.html",
    redirect: "/views/env/Linux%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    name: "v-37df5e3e",
    path: "/views/basic/CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37df5e3e").then(next)
    },
  },
  {
    name: "v-76e41a70",
    path: "/views/basic/HTML.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76e41a70").then(next)
    },
  },
  {
    name: "v-1876c489",
    path: "/views/env/nvm%E5%AE%89%E8%A3%85node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1876c489").then(next)
    },
  },
  {
    path: "/views/env/nvm安装node.html",
    redirect: "/views/env/nvm%E5%AE%89%E8%A3%85node.html"
  },
  {
    path: "/views/env/nvm安装node.html",
    redirect: "/views/env/nvm%E5%AE%89%E8%A3%85node.html"
  },
  {
    name: "v-901301a8",
    path: "/views/env/Nginx%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-901301a8").then(next)
    },
  },
  {
    path: "/views/env/Nginx基础.html",
    redirect: "/views/env/Nginx%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/views/env/Nginx基础.html",
    redirect: "/views/env/Nginx%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-2f38755c",
    path: "/views/env/vscode%E6%8B%93%E5%B1%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f38755c").then(next)
    },
  },
  {
    path: "/views/env/vscode拓展.html",
    redirect: "/views/env/vscode%E6%8B%93%E5%B1%95.html"
  },
  {
    path: "/views/env/vscode拓展.html",
    redirect: "/views/env/vscode%E6%8B%93%E5%B1%95.html"
  },
  {
    name: "v-a83d4764",
    path: "/views/basic/JavaScript%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a83d4764").then(next)
    },
  },
  {
    path: "/views/basic/JavaScript基础.html",
    redirect: "/views/basic/JavaScript%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/views/basic/JavaScript基础.html",
    redirect: "/views/basic/JavaScript%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-a6b83772",
    path: "/views/env/vscode%20%E5%BF%AB%E6%8D%B7%E7%94%9F%E6%88%90vue%E6%A8%A1%E6%9D%BF%E9%A1%B5%E9%9D%A2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6b83772").then(next)
    },
  },
  {
    path: "/views/env/vscode 快捷生成vue模板页面.html",
    redirect: "/views/env/vscode%20%E5%BF%AB%E6%8D%B7%E7%94%9F%E6%88%90vue%E6%A8%A1%E6%9D%BF%E9%A1%B5%E9%9D%A2.html"
  },
  {
    path: "/views/env/vscode 快捷生成vue模板页面.html",
    redirect: "/views/env/vscode%20%E5%BF%AB%E6%8D%B7%E7%94%9F%E6%88%90vue%E6%A8%A1%E6%9D%BF%E9%A1%B5%E9%9D%A2.html"
  },
  {
    name: "v-b12035e4",
    path: "/views/node/nodejs2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b12035e4").then(next)
    },
  },
  {
    name: "v-0d23ec38",
    path: "/views/node/express1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d23ec38").then(next)
    },
  },
  {
    name: "v-6a082be5",
    path: "/views/env/LINUX%E5%AE%89%E8%A3%85nginx.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a082be5").then(next)
    },
  },
  {
    path: "/views/env/LINUX安装nginx.html",
    redirect: "/views/env/LINUX%E5%AE%89%E8%A3%85nginx.html"
  },
  {
    path: "/views/env/LINUX安装nginx.html",
    redirect: "/views/env/LINUX%E5%AE%89%E8%A3%85nginx.html"
  },
  {
    name: "v-3828a958",
    path: "/views/node/express2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3828a958").then(next)
    },
  },
  {
    name: "v-2e4d02da",
    path: "/views/node/socket.io.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e4d02da").then(next)
    },
  },
  {
    name: "v-962bf5e0",
    path: "/views/node/nodejs1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-962bf5e0").then(next)
    },
  },
  {
    name: "v-862618a2",
    path: "/views/node/websocket%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-862618a2").then(next)
    },
  },
  {
    path: "/views/node/websocket基本使用.html",
    redirect: "/views/node/websocket%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.html"
  },
  {
    path: "/views/node/websocket基本使用.html",
    redirect: "/views/node/websocket%E5%9F%BA%E6%9C%AC%E4%BD%BF%E7%94%A8.html"
  },
  {
    name: "v-7ebf0200",
    path: "/views/node/sql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ebf0200").then(next)
    },
  },
  {
    name: "v-6ced97ef",
    path: "/views/project/%E4%B8%8A%E6%B5%B7%E9%93%B6%E8%A1%8C%E6%8E%92%E9%98%9F%E9%A1%B9%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ced97ef").then(next)
    },
  },
  {
    path: "/views/project/上海银行排队项目.html",
    redirect: "/views/project/%E4%B8%8A%E6%B5%B7%E9%93%B6%E8%A1%8C%E6%8E%92%E9%98%9F%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: "/views/project/上海银行排队项目.html",
    redirect: "/views/project/%E4%B8%8A%E6%B5%B7%E9%93%B6%E8%A1%8C%E6%8E%92%E9%98%9F%E9%A1%B9%E7%9B%AE.html"
  },
  {
    name: "v-dc15e926",
    path: "/views/other/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dc15e926").then(next)
    },
  },
  {
    path: "/views/other/环境变量.html",
    redirect: "/views/other/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F.html"
  },
  {
    path: "/views/other/环境变量.html",
    redirect: "/views/other/%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F.html"
  },
  {
    name: "v-fce0bab2",
    path: "/views/project/%E6%9F%9C%E9%9D%A2poc%E9%A1%B9%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fce0bab2").then(next)
    },
  },
  {
    path: "/views/project/柜面poc项目.html",
    redirect: "/views/project/%E6%9F%9C%E9%9D%A2poc%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: "/views/project/柜面poc项目.html",
    redirect: "/views/project/%E6%9F%9C%E9%9D%A2poc%E9%A1%B9%E7%9B%AE.html"
  },
  {
    name: "v-165c5e44",
    path: "/views/study/task2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-165c5e44").then(next)
    },
  },
  {
    name: "v-8c683104",
    path: "/views/study/task1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c683104").then(next)
    },
  },
  {
    name: "v-152d85f9",
    path: "/views/uniapp/request%E5%B0%81%E8%A3%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-152d85f9").then(next)
    },
  },
  {
    path: "/views/uniapp/request封装.html",
    redirect: "/views/uniapp/request%E5%B0%81%E8%A3%85.html"
  },
  {
    path: "/views/uniapp/request封装.html",
    redirect: "/views/uniapp/request%E5%B0%81%E8%A3%85.html"
  },
  {
    name: "v-1c246fe9",
    path: "/views/other/%E5%B8%83%E5%B1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c246fe9").then(next)
    },
  },
  {
    path: "/views/other/布局.html",
    redirect: "/views/other/%E5%B8%83%E5%B1%80.html"
  },
  {
    path: "/views/other/布局.html",
    redirect: "/views/other/%E5%B8%83%E5%B1%80.html"
  },
  {
    name: "v-375f6af4",
    path: "/views/uniapp/uniapp%E6%94%AF%E4%BB%98%E5%8A%9F%E8%83%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-375f6af4").then(next)
    },
  },
  {
    path: "/views/uniapp/uniapp支付功能.html",
    redirect: "/views/uniapp/uniapp%E6%94%AF%E4%BB%98%E5%8A%9F%E8%83%BD.html"
  },
  {
    path: "/views/uniapp/uniapp支付功能.html",
    redirect: "/views/uniapp/uniapp%E6%94%AF%E4%BB%98%E5%8A%9F%E8%83%BD.html"
  },
  {
    name: "v-4a607284",
    path: "/views/vue/vue2%E5%92%8Cvue3%E7%9A%84%E5%8C%BA%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a607284").then(next)
    },
  },
  {
    path: "/views/vue/vue2和vue3的区别.html",
    redirect: "/views/vue/vue2%E5%92%8Cvue3%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    path: "/views/vue/vue2和vue3的区别.html",
    redirect: "/views/vue/vue2%E5%92%8Cvue3%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    name: "v-9b8d3b84",
    path: "/views/vue/vue3%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9b8d3b84").then(next)
    },
  },
  {
    path: "/views/vue/vue3基础.html",
    redirect: "/views/vue/vue3%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/views/vue/vue3基础.html",
    redirect: "/views/vue/vue3%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-0a6d30a2",
    path: "/views/question/%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95%E9%A2%98%E6%95%B4%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a6d30a2").then(next)
    },
  },
  {
    path: "/views/question/前端面试题整合.html",
    redirect: "/views/question/%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95%E9%A2%98%E6%95%B4%E5%90%88.html"
  },
  {
    path: "/views/question/前端面试题整合.html",
    redirect: "/views/question/%E5%89%8D%E7%AB%AF%E9%9D%A2%E8%AF%95%E9%A2%98%E6%95%B4%E5%90%88.html"
  },
  {
    name: "v-fd26f848",
    path: "/views/project/%E5%BE%AE%E4%BF%A1%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fd26f848").then(next)
    },
  },
  {
    path: "/views/project/微信管理平台.html",
    redirect: "/views/project/%E5%BE%AE%E4%BF%A1%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0.html"
  },
  {
    path: "/views/project/微信管理平台.html",
    redirect: "/views/project/%E5%BE%AE%E4%BF%A1%E7%AE%A1%E7%90%86%E5%B9%B3%E5%8F%B0.html"
  },
  {
    name: "v-60e93674",
    path: "/views/uniapp/uniapp%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60e93674").then(next)
    },
  },
  {
    path: "/views/uniapp/uniapp基础.html",
    redirect: "/views/uniapp/uniapp%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/views/uniapp/uniapp基础.html",
    redirect: "/views/uniapp/uniapp%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-265db216",
    path: "/views/vue/vue3%E9%A1%B9%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-265db216").then(next)
    },
  },
  {
    path: "/views/vue/vue3项目.html",
    redirect: "/views/vue/vue3%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: "/views/vue/vue3项目.html",
    redirect: "/views/vue/vue3%E9%A1%B9%E7%9B%AE.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]