<template><div><h1 id="作业二" tabindex="-1"><a class="header-anchor" href="#作业二" aria-hidden="true">#</a> 作业二</h1>
<h2 id="一、准备" tabindex="-1"><a class="header-anchor" href="#一、准备" aria-hidden="true">#</a> 一、准备</h2>
<h3 id="_1-jq使用" tabindex="-1"><a class="header-anchor" href="#_1-jq使用" aria-hidden="true">#</a> 1.jq使用</h3>
<p>等页面加载完毕之后，才开始执行函数</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token function">$</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_2-适配" tabindex="-1"><a class="header-anchor" href="#_2-适配" aria-hidden="true">#</a> 2.适配</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>    <span class="token keyword">var</span> <span class="token function-variable function">initScreen</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">callback</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//初始化html  font-size</span>
        <span class="token keyword">var</span> _fontsize <span class="token operator">=</span> <span class="token number">625</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientWidth <span class="token operator">&lt;</span> <span class="token number">1400</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            _fontsize <span class="token operator">=</span> <span class="token number">1400</span> <span class="token operator">/</span> <span class="token number">1920</span> <span class="token operator">*</span> <span class="token number">625</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientWidth <span class="token operator">/</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientHeight <span class="token operator">></span> <span class="token number">3</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            _fontsize <span class="token operator">=</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientHeight <span class="token operator">*</span> <span class="token number">3</span> <span class="token operator">/</span> <span class="token number">1920</span> <span class="token operator">*</span> <span class="token number">625</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">else</span> <span class="token punctuation">{</span>
            _fontsize <span class="token operator">=</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientWidth <span class="token operator">/</span> <span class="token number">1920</span> <span class="token operator">*</span> <span class="token number">625</span>
        <span class="token punctuation">}</span>
        <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">"html"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">css</span><span class="token punctuation">(</span><span class="token string">"font-size"</span><span class="token punctuation">,</span> _fontsize <span class="token operator">+</span> <span class="token string">"%"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span>callback<span class="token punctuation">)</span> <span class="token function">callback</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token function">initScreen</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">$</span><span class="token punctuation">(</span>window<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">resize</span><span class="token punctuation">(</span><span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token function">initScreen</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token function">initScreen</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、其他" tabindex="-1"><a class="header-anchor" href="#二、其他" aria-hidden="true">#</a> 二、其他</h2>
<h3 id="_1-模板字符串" tabindex="-1"><a class="header-anchor" href="#_1-模板字符串" aria-hidden="true">#</a> 1.模板字符串</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> url <span class="token operator">=</span> <span class="token function">require</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">../../img/</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>szUrl1<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">/stand</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>e<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">0</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>num<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">.png</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_2-图片预加载" tabindex="-1"><a class="header-anchor" href="#_2-图片预加载" aria-hidden="true">#</a> 2.图片预加载</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>    <span class="token keyword">function</span> <span class="token function">preloadimages</span><span class="token punctuation">(</span><span class="token parameter">arr</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">var</span> newimages <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> loadedimages <span class="token operator">=</span> <span class="token number">0</span>
        <span class="token keyword">var</span> <span class="token function-variable function">postaction</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token punctuation">}</span>  <span class="token comment">//此处增加了一个postaction函数</span>
        <span class="token keyword">var</span> arr <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token keyword">typeof</span> arr <span class="token operator">!=</span> <span class="token string">"object"</span><span class="token punctuation">)</span> <span class="token operator">?</span> <span class="token punctuation">[</span>arr<span class="token punctuation">]</span> <span class="token operator">:</span> arr
        <span class="token keyword">function</span> <span class="token function">imageloadpost</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            loadedimages<span class="token operator">++</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>loadedimages <span class="token operator">==</span> arr<span class="token punctuation">.</span>length<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">postaction</span><span class="token punctuation">(</span>newimages<span class="token punctuation">)</span> <span class="token comment">//加载完成用我们调用postaction函数并将newimages数组做为参数传递进去</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> arr<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            newimages<span class="token punctuation">[</span>i<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Image</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            newimages<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>src <span class="token operator">=</span> arr<span class="token punctuation">[</span>i<span class="token punctuation">]</span>
            newimages<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function-variable function">onload</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">imageloadpost</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
            newimages<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function-variable function">onerror</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token function">imageloadpost</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
        <span class="token keyword">return</span> <span class="token punctuation">{</span> <span class="token comment">//此处返回一个空白对象的done方法</span>
            <span class="token function-variable function">done</span><span class="token operator">:</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">f</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
                postaction <span class="token operator">=</span> f <span class="token operator">||</span> postaction
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-读取文件夹中内容" tabindex="-1"><a class="header-anchor" href="#_3-读取文件夹中内容" aria-hidden="true">#</a> 3.读取文件夹中内容</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>    <span class="token keyword">let</span> img_list <span class="token operator">=</span> <span class="token function">__resload</span><span class="token punctuation">(</span><span class="token string">'img/boy'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>img_list<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_4-less中的css动画函数" tabindex="-1"><a class="header-anchor" href="#_4-less中的css动画函数" aria-hidden="true">#</a> 4.less中的css动画函数</h3>
<div class="language-less line-numbers-mode" data-ext="less"><pre v-pre class="language-less"><code><span class="token selector">.keyframesFunction1  (<span class="token variable">@name</span>,<span class="token variable">@url</span>)</span><span class="token punctuation">{</span>
    <span class="token atrule">@keyframes @name</span> <span class="token punctuation">{</span>
      <span class="token selector">0%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span>~<span class="token string">"url(@{url}00.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">12.5%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span> ~<span class="token string">"url(@{url}01.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">25%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span>~<span class="token string">"url(@{url}02.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">37.5%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span> ~<span class="token string">"url(@{url}03.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">50%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span>~<span class="token string">"url(@{url}04.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">62.5%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span> ~<span class="token string">"url(@{url}05.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">75%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span>~<span class="token string">"url(@{url}06.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">87.5%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span> ~<span class="token string">"url(@{url}07.png)"</span><span class="token punctuation">}</span>
      <span class="token selector">100%</span><span class="token punctuation">{</span><span class="token property">background-image</span><span class="token punctuation">:</span>~<span class="token string">"url(@{url}00.png)"</span><span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span>

<span class="token selector">.animak1</span><span class="token punctuation">{</span>
    <span class="token variable">@url<span class="token punctuation">:</span></span><span class="token string">'../img/kl2/stand00'</span><span class="token punctuation">;</span>
    <span class="token mixin-usage function">.keyframesFunction1</span><span class="token punctuation">(</span>stepk1<span class="token punctuation">,</span><span class="token variable">@url</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token property">animation</span><span class="token punctuation">:</span> stepk1 1s infinite<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_5-控制video" tabindex="-1"><a class="header-anchor" href="#_5-控制video" aria-hidden="true">#</a> 5.控制video</h3>
<p>jq操作video</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'#video2'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">play</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'#video2'</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">'ended'</span><span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span> <span class="token comment">//播放结束监听</span>
            <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'#videoB1'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">show</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
            <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'#videoB2'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">hide</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


