<template><div><h1 id="作业一" tabindex="-1"><a class="header-anchor" href="#作业一" aria-hidden="true">#</a> 作业一</h1>
<h2 id="一、准备" tabindex="-1"><a class="header-anchor" href="#一、准备" aria-hidden="true">#</a> 一、准备</h2>
<h3 id="_1-框架" tabindex="-1"><a class="header-anchor" href="#_1-框架" aria-hidden="true">#</a> 1.框架</h3>
<p>webpack+原生html+jQuery</p>
<h3 id="_2-引入" tabindex="-1"><a class="header-anchor" href="#_2-引入" aria-hidden="true">#</a> 2.引入</h3>
<p>首页引入默认样式及jq</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token operator">&lt;</span>link rel<span class="token operator">=</span><span class="token string">"stylesheet"</span> href<span class="token operator">=</span><span class="token string">"https://nie.res.netease.com/comm/css/art.com.css"</span> <span class="token operator">/</span><span class="token operator">></span>
<span class="token operator">&lt;</span>script charset<span class="token operator">=</span><span class="token string">"utf-8"</span> src<span class="token operator">=</span><span class="token string">"https://nie.res.netease.com/comm/js/jquery(mixNIE).1.11.js"</span><span class="token operator">></span><span class="token operator">&lt;</span><span class="token operator">/</span>script<span class="token operator">></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-rem适配" tabindex="-1"><a class="header-anchor" href="#_3-rem适配" aria-hidden="true">#</a> 3.rem适配</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>        <span class="token comment">// 设置rem</span>
        <span class="token keyword">function</span> <span class="token function">watchWindowSize</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token comment">// 设置字体大小 1px=0.01rem</span>
            <span class="token keyword">var</span> w <span class="token operator">=</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientWidth<span class="token punctuation">;</span>
            <span class="token keyword">var</span> h <span class="token operator">=</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientHeight<span class="token punctuation">;</span>
            console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>w<span class="token punctuation">,</span> h<span class="token punctuation">)</span>
            document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>style<span class="token punctuation">.</span>fontSize <span class="token operator">=</span> w <span class="token operator">/</span> <span class="token number">19.2</span> <span class="token operator">+</span> <span class="token string">'px'</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token comment">// 将事件侦听器函数附加到窗口的resize事件</span>
        window<span class="token punctuation">.</span><span class="token function">addEventListener</span><span class="token punctuation">(</span><span class="token string">"resize"</span><span class="token punctuation">,</span> watchWindowSize<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// 调用该函数</span>
        <span class="token function">watchWindowSize</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="二、jquery使用" tabindex="-1"><a class="header-anchor" href="#二、jquery使用" aria-hidden="true">#</a> 二、jQuery使用</h2>
<h3 id="_1-jq在线文档" tabindex="-1"><a class="header-anchor" href="#_1-jq在线文档" aria-hidden="true">#</a> 1. jq在线文档</h3>
<p>http://hemin.cn/jq/</p>
<h3 id="_2-jq动画" tabindex="-1"><a class="header-anchor" href="#_2-jq动画" aria-hidden="true">#</a> 2.jq动画</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token comment">// 向下滑动图标动画</span>
<span class="token keyword">var</span> xiaB <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token literal-property property">bottom</span><span class="token operator">:</span> <span class="token string">'20rem'</span> <span class="token punctuation">}</span>
<span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'.xia_img-box'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">animate</span><span class="token punctuation">(</span>xiaB<span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">,</span> rowBack<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">function</span> <span class="token function">rowBack</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>xiaB<span class="token punctuation">.</span>bottom <span class="token operator">==</span> <span class="token string">'20rem'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        xiaB<span class="token punctuation">.</span>bottom <span class="token operator">=</span> <span class="token string">'30rem'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token keyword">if</span> <span class="token punctuation">(</span>xiaB<span class="token punctuation">.</span>bottom <span class="token operator">==</span> <span class="token string">'30rem'</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        xiaB<span class="token punctuation">.</span>bottom <span class="token operator">=</span> <span class="token string">'20rem'</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'.xia_img-box'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">animate</span><span class="token punctuation">(</span>xiaB<span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">,</span> rowBack<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-jq循环绑定事件" tabindex="-1"><a class="header-anchor" href="#_3-jq循环绑定事件" aria-hidden="true">#</a> 3.jq循环绑定事件</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>$<span class="token punctuation">.</span><span class="token function">each</span><span class="token punctuation">(</span>navList<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">i<span class="token punctuation">,</span> item</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token function">$</span><span class="token punctuation">(</span>id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token string">"click"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">index</span><span class="token operator">:</span> i<span class="token punctuation">,</span> <span class="token literal-property property">id</span><span class="token operator">:</span> id <span class="token punctuation">}</span><span class="token punctuation">,</span> clickHandler<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token function">$</span><span class="token punctuation">(</span>id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token string">"mouseenter"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">index</span><span class="token operator">:</span> i<span class="token punctuation">,</span> <span class="token literal-property property">id</span><span class="token operator">:</span> id <span class="token punctuation">}</span><span class="token punctuation">,</span> enterHandler<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token function">$</span><span class="token punctuation">(</span>id<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">bind</span><span class="token punctuation">(</span><span class="token string">"mouseleave"</span><span class="token punctuation">,</span> <span class="token punctuation">{</span> <span class="token literal-property property">index</span><span class="token operator">:</span> i<span class="token punctuation">,</span> <span class="token literal-property property">id</span><span class="token operator">:</span> id <span class="token punctuation">}</span><span class="token punctuation">,</span> leaveHandler<span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span> <span class="token number">50</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="三、swiper" tabindex="-1"><a class="header-anchor" href="#三、swiper" aria-hidden="true">#</a> 三、swiper</h2>
<h3 id="_1-引入" tabindex="-1"><a class="header-anchor" href="#_1-引入" aria-hidden="true">#</a> 1.引入</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> Swiper <span class="token keyword">from</span> <span class="token string">"../lib/swiper-bundle"</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_2-使用" tabindex="-1"><a class="header-anchor" href="#_2-使用" aria-hidden="true">#</a> 2.使用</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">var</span> swiper <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Swiper</span><span class="token punctuation">(</span><span class="token string">'#swiper-page'</span><span class="token punctuation">,</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">mousewheel</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">//鼠标滚动</span>
    <span class="token literal-property property">direction</span><span class="token operator">:</span> <span class="token string">'vertical'</span><span class="token punctuation">,</span> <span class="token comment">//竖直方向</span>
    <span class="token literal-property property">allowSlidePrev</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">//可向左或上滑动。</span>
    <span class="token literal-property property">mousewheel</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">releaseOnEdges</span><span class="token operator">:</span> <span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token comment">//PC端释放滑动    </span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_3-方法" tabindex="-1"><a class="header-anchor" href="#_3-方法" aria-hidden="true">#</a> 3.方法</h3>
<p>滚动到指定页面</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>swiper<span class="token punctuation">.</span><span class="token function">slideTo</span><span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token number">1000</span><span class="token punctuation">,</span> <span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_4-其他参数" tabindex="-1"><a class="header-anchor" href="#_4-其他参数" aria-hidden="true">#</a> 4.其他参数</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token literal-property property">slidesPerView</span><span class="token operator">:</span> <span class="token number">3</span><span class="token punctuation">,</span> <span class="token comment">//展示3项</span>
<span class="token literal-property property">navigation</span><span class="token operator">:</span> <span class="token punctuation">{</span>  <span class="token comment">//导航箭头</span>
        <span class="token literal-property property">nextEl</span><span class="token operator">:</span> <span class="token string">'.img-right'</span><span class="token punctuation">,</span>
        <span class="token literal-property property">prevEl</span><span class="token operator">:</span> <span class="token string">'.img-left'</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_5-监听函数" tabindex="-1"><a class="header-anchor" href="#_5-监听函数" aria-hidden="true">#</a> 5.监听函数</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>    <span class="token literal-property property">on</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token function">slideChangeTransitionEnd</span><span class="token punctuation">(</span><span class="token parameter">swiper</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token function">setActive</span><span class="token punctuation">(</span>swiper<span class="token punctuation">.</span>activeIndex<span class="token punctuation">)</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="四、其他js相关" tabindex="-1"><a class="header-anchor" href="#四、其他js相关" aria-hidden="true">#</a> 四、其他js相关</h2>
<h3 id="_1-隐藏滚动条" tabindex="-1"><a class="header-anchor" href="#_1-隐藏滚动条" aria-hidden="true">#</a> 1.隐藏滚动条</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>style<span class="token punctuation">.</span>overflowY <span class="token operator">=</span> <span class="token string">'hidden'</span><span class="token punctuation">;</span>
document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>style<span class="token punctuation">.</span>overflowX <span class="token operator">=</span> <span class="token string">'hidden'</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_2-跳转页面" tabindex="-1"><a class="header-anchor" href="#_2-跳转页面" aria-hidden="true">#</a> 2.跳转页面</h3>
<p>跳转页面，新窗口打开</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>window<span class="token punctuation">.</span><span class="token function">open</span><span class="token punctuation">(</span><span class="token string">'https://xyqh5.163.com/index.html'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p>当前页面打开</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>window<span class="token punctuation">.</span>location<span class="token punctuation">.</span>href <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token string">'./index.html'</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="_3-nicescroll使用" tabindex="-1"><a class="header-anchor" href="#_3-nicescroll使用" aria-hidden="true">#</a> 3.niceScroll使用</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token string">"../lib/nicescroll"</span>

<span class="token function">$</span><span class="token punctuation">(</span><span class="token string">".content"</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">niceScroll</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token literal-property property">cursorcolor</span><span class="token operator">:</span> <span class="token string">"#A5D4D5"</span><span class="token punctuation">,</span>
    <span class="token literal-property property">background</span><span class="token operator">:</span> <span class="token string">"#ECDDBC"</span><span class="token punctuation">,</span> <span class="token comment">// 轨道的背景颜色</span>
    <span class="token literal-property property">cursorwidth</span><span class="token operator">:</span> <span class="token string">"3rem"</span><span class="token punctuation">,</span> <span class="token comment">// 滚动条的宽度，单位：便素</span>
    <span class="token literal-property property">cursorborder</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span> <span class="token comment">// CSS方式定义滚动条边框</span>
    <span class="token literal-property property">autohidemode</span><span class="token operator">:</span> <span class="token string">'leave'</span><span class="token punctuation">,</span> <span class="token comment">// 'leave'  false</span>
    <span class="token literal-property property">zindex</span><span class="token operator">:</span> <span class="token number">99</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="_4-监听元素距离顶部" tabindex="-1"><a class="header-anchor" href="#_4-监听元素距离顶部" aria-hidden="true">#</a> 4.监听元素距离顶部</h3>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>        <span class="token function">handleScroll</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">var</span> scrollTop <span class="token operator">=</span> document<span class="token punctuation">.</span>body<span class="token punctuation">.</span>scrollTop <span class="token operator">||</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>scrollTop
            <span class="token keyword">var</span> ch <span class="token operator">=</span> document<span class="token punctuation">.</span>documentElement<span class="token punctuation">.</span>clientHeight
            <span class="token keyword">var</span> h <span class="token operator">=</span> <span class="token function">$</span><span class="token punctuation">(</span><span class="token string">'#foot'</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">offset</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span>top
            <span class="token comment">// console.log(scrollTop,h,ch,this.fixNav)</span>
            <span class="token keyword">if</span> <span class="token punctuation">(</span>scrollTop <span class="token operator">&lt;</span> h <span class="token operator">-</span> ch<span class="token punctuation">)</span> <span class="token punctuation">{</span>
                <span class="token keyword">this</span><span class="token punctuation">.</span>fixNav <span class="token operator">=</span> <span class="token boolean">true</span>
            <span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
                <span class="token keyword">this</span><span class="token punctuation">.</span>fixNav <span class="token operator">=</span> <span class="token boolean">false</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
        window<span class="token punctuation">.</span><span class="token function-variable function">onscroll</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            _this<span class="token punctuation">.</span><span class="token function">handleScroll</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


