<template><div><h1 id="金融" tabindex="-1"><a class="header-anchor" href="#金融" aria-hidden="true">#</a> 金融</h1>
<h2 id="基础名词" tabindex="-1"><a class="header-anchor" href="#基础名词" aria-hidden="true">#</a> 基础名词</h2>
<table>
<thead>
<tr>
<th>名词</th>
<th>定义</th>
</tr>
</thead>
<tbody>
<tr>
<td>资本</td>
<td>指用于投资和经营的货币或财产。</td>
</tr>
<tr>
<td>利率</td>
<td>借贷资金的成本或回报率。</td>
</tr>
<tr>
<td>股票</td>
<td>公司向公众发行的所有权证券。</td>
</tr>
<tr>
<td>债券</td>
<td>公司或政府向投资者发行的借款工具。</td>
</tr>
<tr>
<td>期货</td>
<td>在未来某一特定时间点交割的标准化合约。</td>
</tr>
<tr>
<td>期权</td>
<td>购买或出售某种资产的权利，但不是义务。</td>
</tr>
<tr>
<td>外汇</td>
<td>不同国家货币之间的兑换。</td>
</tr>
<tr>
<td>银行</td>
<td>提供存款、贷款和其他金融服务的金融机构。</td>
</tr>
<tr>
<td>投资基金</td>
<td>由投资者共同出资组成的基金，用于投资各种资产。</td>
</tr>
<tr>
<td>保险</td>
<td>通过支付保费来获得对风险和损失的保障。</td>
</tr>
<tr>
<td>财务报表</td>
<td>反映企业财务状况和业绩的文件，如资产负债表、利润表和现金流量表。</td>
</tr>
<tr>
<td>经济周期</td>
<td>经济活动波动的周期性变化，包括繁荣、衰退、萧条和复苏</td>
</tr>
</tbody>
</table>
<h2 id="理财产品" tabindex="-1"><a class="header-anchor" href="#理财产品" aria-hidden="true">#</a> 理财产品</h2>
<table>
<thead>
<tr>
<th>理财产品</th>
<th>描述</th>
</tr>
</thead>
<tbody>
<tr>
<td>储蓄账户</td>
<td>一种安全的存款方式，通常由银行提供，以较低的利率获取相对稳定的回报。</td>
</tr>
<tr>
<td>定期存款</td>
<td>将资金存入银行一段固定时间（如几个月或几年），以较高的利率获得固定回报。</td>
</tr>
<tr>
<td>货币市场基金</td>
<td>由资金管理公司设立的一种基金，投资于短期、低风险的债券和货币市场工具。</td>
</tr>
<tr>
<td>债券基金</td>
<td>投资于各类债券，包括政府债券、公司债券和地方债券等，通过债券获得固定收益。</td>
</tr>
<tr>
<td>股票基金</td>
<td>通过投资于多只股票构成的投资组合，让投资者分享股票市场的收益和风险。</td>
</tr>
<tr>
<td>指数基金</td>
<td>跟踪特定市场指数的基金，通过购买指数成分股来复制指数的表现。</td>
</tr>
<tr>
<td>混合型基金</td>
<td>投资于多种不同资产类别，如股票、债券和现金，以实现资产配置的多样化。</td>
</tr>
<tr>
<td>理财计划</td>
<td>由银行或其他金融机构推出的结构化投资产品，通常具有一定期限和预期回报。</td>
</tr>
<tr>
<td>保险产品</td>
<td>如寿险和养老金等，提供风险保障和长期储蓄功能。</td>
</tr>
<tr>
<td>外汇交易</td>
<td>通过买卖不同货币之间的汇率变动，追求汇率差价获利的投资方式。</td>
</tr>
</tbody>
</table>
</div></template>


