<template><div><h1 id="海南柜面项目" tabindex="-1"><a class="header-anchor" href="#海南柜面项目" aria-hidden="true">#</a> 海南柜面项目</h1>
<p>开发周期：202308-至今</p>
<p>项目概要：一个超级大系统，有管理端、开发者端、桌面端、配套工具（ide）</p>
<p>评价：</p>
<p>难度：⭐⭐</p>
<p>繁琐程度：⭐⭐⭐⭐</p>
<p>知识点：</p>
<ul>
<li>组件的设计与封装</li>
</ul>
<h2 id="_20240311" tabindex="-1"><a class="header-anchor" href="#_20240311" aria-hidden="true">#</a> 20240311</h2>
<h3 id="组件封装" tabindex="-1"><a class="header-anchor" href="#组件封装" aria-hidden="true">#</a> 组件封装</h3>
<table>
<thead>
<tr>
<th>组件序号</th>
<th>组件中文名称</th>
<th>组件英文名称</th>
<th>说明</th>
</tr>
</thead>
<tbody>
<tr>
<td>1</td>
<td>代理人</td>
<td>nt-agent</td>
<td>代理人功能组件</td>
</tr>
<tr>
<td>2</td>
<td>查询列表筛选结果组件</td>
<td>nt-querylist</td>
<td>1.提供属性接收查询方法，支持全量查询/分页查询<br />2.根据查询方法，提供客户端/服务端分页功能(客户端：前端逻辑展示分页数据；服务端：分页要素改变调用查询接口展示数据)<br />3.提供按全列/指定列导出、打印功能，可由开发自定义是否使用（默认使用）<br />4.提供根据列名筛选查询结果功能<br />5.提供增加自定义操作列功能，比如在列表中增加操作按钮<br />6.提供选中单行数据/多行数据的功能，可由开发自定义是否使用（默认使用）<br />7.提供按指定列排序功能 <br />8.提供根据列内容自动扩展列宽的功能</td>
</tr>
<tr>
<td>1</td>
<td>交易提交业务组件</td>
<td>nt-submit-business</td>
<td>1.实现防重提交。</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td>2.默认走收费逻辑、授权逻辑、打印逻辑等公共业务逻辑</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td>3.提供给各个开发人员编写自定义逻辑的功能</td>
</tr>
<tr>
<td>1</td>
<td>手机号</td>
<td>nt-input-mobile</td>
<td>1.不少于11位手机号，数字格式</td>
</tr>
<tr>
<td>1</td>
<td>行政区划</td>
<td>nt-input-adminarea</td>
<td></td>
</tr>
<tr>
<td>2</td>
<td>联网核查</td>
<td>nt-onlinecheck</td>
<td>1.联网核查功能组件</td>
</tr>
<tr>
<td>2</td>
<td>客户视图</td>
<td>nt-custerview</td>
<td>1.客户视图展示组件</td>
</tr>
<tr>
<td>2</td>
<td>凭证打印</td>
<td>nt-vouchprint</td>
<td>1.</td>
</tr>
<tr>
<td>3</td>
<td>验印核查</td>
<td>nt-verificacheck</td>
<td></td>
</tr>
<tr>
<td>2</td>
<td>网上预约信息</td>
<td>nt-onlinereserinfo</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>客户账号</td>
<td>nt-input-account</td>
<td>1.可设置通过设备获取</td>
</tr>
<tr>
<td>1</td>
<td>密码</td>
<td>nt-input-password</td>
<td>1.密码长度、密码是否设备获取等</td>
</tr>
<tr>
<td>1</td>
<td>个人证件号码</td>
<td>nt-input-personidnum</td>
<td>1. 证件号码字母自动转为大写（开关）</td>
</tr>
<tr>
<td>1</td>
<td></td>
<td></td>
<td>2.长度18位，输入时在框体后显示文本内容长度（开关）</td>
</tr>
<tr>
<td>1</td>
<td></td>
<td></td>
<td>3.提供调用读卡器控制配置，打开则弹窗提示是否使用设备采集证件数据，是：使用设备 否：手输 选择是调用设备获取信息</td>
</tr>
<tr>
<td>1</td>
<td></td>
<td></td>
<td>4.提供给各个开发人员编写自定义逻辑的功能，支持自定义逻辑中进行接口、控件的调用判断，如可调用核心证件号码验证接口、联网核查控件、其他控件功能联动等；</td>
</tr>
<tr>
<td>1</td>
<td>对公证件号码</td>
<td>nt-input-companynum</td>
<td>1. 证件号码字母自动转为大写（开关）</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td>2.长度18位，输入时在框体后显示文本内容长度（开关）</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td>3.提供调用读卡器控制配置，打开则弹窗提示是否使用设备采集证件数据，是：使用设备 否：手输 选择是调用设备获取信息</td>
</tr>
<tr>
<td></td>
<td></td>
<td></td>
<td>4.提供给各个开发人员编写自定义逻辑的功能，支持自定义逻辑中进行接口、控件的调用判断，如可调用核心证件号码验证接口、联网核查控件、其他控件功能联动等；</td>
</tr>
<tr>
<td>1</td>
<td>币种</td>
<td>nt-select-currency</td>
<td>1.币种下拉框：[序号]中文名 [01]人民币 中文名 序号 货币符号 人民币 01 CNY<br /> 英 镑 12 GBP <br />美 元 13 USD <br />瑞士法郎 15 CHF <br />新加坡元 18 SGD <br />日 元 27 JPY <br />加拿大元 28 CAD <br />澳大利亚元 29 AUD <br />欧 元 38 EUR <br />卢 布 90 RUB <br />现场开发</td>
</tr>
<tr>
<td>1</td>
<td>金额</td>
<td>nt-input-money</td>
<td>2位小数，控件内容前三位默认为货币符号CNY，展示效果为CNY0.00与币种控件联动，选择不同币种货币符号改变</td>
</tr>
<tr>
<td>1</td>
<td>固定电话</td>
<td>nt-input-telphone</td>
<td>固定电话号码大于等于7位</td>
</tr>
<tr>
<td>1</td>
<td>地区编码</td>
<td>nt-input-regioncode</td>
<td>地区编码定长4位校验</td>
</tr>
<tr>
<td>1</td>
<td>时间日期（日历组件）</td>
<td>nt-input-singledate</td>
<td>时间单独使用，如生日日期，8位</td>
</tr>
<tr>
<td>1</td>
<td>开始日期、结束日期</td>
<td>nt-input-begindate、nt-input-enddate</td>
<td>默认不弹出日期选择框</td>
</tr>
<tr>
<td>1</td>
<td></td>
<td></td>
<td>可手工输入不带格式日期，如20240111</td>
</tr>
<tr>
<td>1</td>
<td></td>
<td></td>
<td>开始日期一定小于等于结束日期，提供开发自行选择开始日期是否等于结束日期</td>
</tr>
<tr>
<td>1</td>
<td></td>
<td></td>
<td>提供开发自行选择是否允许等于当天</td>
</tr>
<tr>
<td>1</td>
<td>组织机构代码</td>
<td>nt-input-organizationcode</td>
<td>对公组织机构代码校验，提供可自定义的校验规则</td>
</tr>
<tr>
<td>1</td>
<td>邮编</td>
<td>nt-input-zipcode</td>
<td>个人邮编非必输，企业邮编必输，定长6位校验</td>
</tr>
<tr>
<td>1</td>
<td>凭证号</td>
<td>nt-input-voucherno</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>利率</td>
<td>nt-input-rate</td>
<td>利率控件，6位小数，控件末尾默认显示%，该符号不参与数值计算</td>
</tr>
<tr>
<td>1</td>
<td>比例</td>
<td>nt-input-proportion</td>
<td>比例控件，2位小数，控件末尾默认显示%，该符号不参与数值计算</td>
</tr>
<tr>
<td>1</td>
<td>证件类型</td>
<td>nt-select-idtype</td>
<td>与证件号码绑定，联动</td>
</tr>
<tr>
<td>1</td>
<td>英文姓名</td>
<td>nt-input-englishname</td>
<td>必须为字母</td>
</tr>
<tr>
<td>1</td>
<td>行业分类</td>
<td>nt-select-Industryclass</td>
<td>提供级联控件，如支持4级，可根据数据格式自行控制层级</td>
</tr>
<tr>
<td>1</td>
<td>底部提示框</td>
<td>nt.showMessageBox</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>弹出提示框</td>
<td></td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>红字提示框</td>
<td>nt.showErrorMessageBoxnt.showTip</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>顶部提示框</td>
<td>nt.message</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>底部询问提示框</td>
<td>nt.showQuestinMessageRox</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>底部决策提示框</td>
<td>nt.showcomfirmBox</td>
<td></td>
</tr>
<tr>
<td>1</td>
<td>双敲输入框</td>
<td>nt-input-repeat</td>
<td>输入一次数据后，按回车后清空输入框，要求再次输入一次；两次输入的内容要求一致。否则提示错误，例如：身份证号要求输入两次</td>
</tr>
</tbody>
</table>
</div></template>


